### PR TITLE
Added command line option for adding accounts. closes #4

### LINKED ISSUE #4: Command line addition of accounts to Config.json
**Description:** 
Right now, if  user want to add link than user have to edit `Config.json`

**Expected Behaviour**
User should able to add links in `config.json` through terminal using some arguments like `python StalkPy.py --add https://example.com`

### PR DESCRIPTION
**Pull request by foxstephen**
Example usage: `python StalkPy.py -u stephenfox1995 -a test:test.com/user/`

### CODE REVIEW

**Comment by vaibhavsingh97** [comment]
@StephenFox1995 Thanks a lot for your PR!! 🎉 However there is already a PR open for the same issue. I don't mind merging this but since ashwani has submitted the PR first so i think that he should get fair chance. How ever, i tested your PR but it's not working as it was expected. I issued 
```
python StalkPy.py -a test:test.com/user/
```
it's giving me the error

```
usage: StalkPy.py [-h] -u USERNAME [USERNAME ...] [-a ADD [ADD ...]]
StalkPy.py: error: the following arguments are required: -u/--username
```
Also, It should be always better to include a screenshot in the PR so that reviewer could get some sort of help and if the PR needed some sort of commands that is executed to run the patch successfully, please mention that 😄

**Comment by foxstephen** [comment]
@vaibhavsingh97 Hi, I left the username as required.

So for example; `python StalkPy.py -u stephenfox1995 -a test:test.com/uuser/` will work.
It will add the new social media link, then perform normal account lookups.

**Comment by vaibhavsingh97** [comment]
@StephenFox1995 Ohh!! can you do without having the username like if i use
`python StalkPy.py -a test:test.com/user/` then it should add this to config.json

**Comment by foxstephen** [comment]
@vaibhavsingh97 Hi wasn't sure if you wanted it as standalone arg as the `--username` arg is required in the current version.

**Comment by vaibhavsingh97** [comment]
@StephenFox1995 Now you know 😄.

**Comment by foxstephen** [comment]
Okay, I have updated to allow `python StalkPy.py -a test:test.com/user/` on its own.

**Comment by vaibhavsingh97** [comment]
@StephenFox1995 Let's wait for ashwani till tomorrow, I he is not able to fix the changes in PR than we will merge this PR. Thanks for contributing 😄

**Comment by ashwini0529** [comment]
Hey @vaibhavsingh97 you can merge his PR. I don't mind. Really sorry. Was about to fix tonight. Was caught up in exams. 😄

**Comment by vaibhavsingh97** [comment]
@StephenFox1995 Thanks for contributing! good work!! Don't forget starred the repository 😉

**Pull request merged**
