### PR TITLE
command line integration to add accounts

### PR DESCRIPTION
**Pull request by ashwini0529**
This allows you to add social accounts using command line. Closes https://github.com/vaibhavsingh97/StalkPy/issues/4

### CODE REVIEW

**Comment by vaibhavsingh97** [comment]
@ashwini0529 This PR is not working as it want to be.
If i use `python StalkPy.py -a test: test.com/` or `python StalkPy.py -a test.com/` then in config .json it added 
```json
    "test.com/": "test.com/",
    "test:test.com/": "test:test.com/",
```
This is not the correct behaviour
it should add 
```
"test" : https://test.com/
```

**Comment by ashwini0529** [comment]
Hey, @vaibhavsingh97 Alright. Will do that by tomorrow! 😄

**Comment by vaibhavsingh97** [comment]
@ashwini0529 Any update? Don't give up 😄

**Comment by vaibhavsingh97** [comment]
@ashwini0529 Thanks for contributing!! Closing since the issue is resolved 😄

**Pull request closed without merging**
